name: Build

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Try release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -x
        tag=$(node -e "console.log('v'+JSON.parse(require('fs').readFileSync('package.json')).version)")
        if ! git show-ref --tags "$tag" --quiet; then
          as="$(printf '{if($1=="##"&&$2=="%s"){F=1;print$2}else if($1!="##"&&F){print$0}else if(F){exit}}' $tag)"
          msg="$(cat CHANGELOG.md | awk "$as")"
          git tag $tag
          git push --tags
          hub release create -m "$msg" "$tag"
        fi
