name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Release macOS
    runs-on: [macos-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn dist
