name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create a release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag_name="${GITHUB_REF##*/}"
        hub release create -m "$tag_name" "$tag_name"

  macos:
    name: Release macOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn
    - run: yarn dist
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        version=$(node -e "console.log(JSON.parse(require('fs').readFileSync('package.json')).version)")
        tag_name="${GITHUB_REF##*/}"
        hub release edit -a dist/DWords-$version.dmg "$tag_name"

  windows:
    name: Release Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn
    - run: yarn dist
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $version=$(node -e "console.log(JSON.parse(require('fs').readFileSync('package.json')).version)")
        $tag_name=$GITHUB_REF.split("/")[-1]
        hub release edit -a "dist\DWords Setup $version.exe" "$tag_name"
