name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  macos:
    name: Release macOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn
    - run: yarn dist
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        version=$(node -e "console.log(JSON.parse(require('fs').readFileSync('package.json')).version)")
        hub release create -a dist/DWords-$version.dmg -m "v$version" "v$version"

  windows:
    name: Release Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn
    - run: yarn dist
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $version=$(node -e "console.log(JSON.parse(require('fs').readFileSync('package.json')).version)")
        hub release create -a dist/DWords-$version.exe -m "v$version" "v$version"
